const state={token:null,role:null,userId:null,challengeId:null,playId:null,sessionId:null,rewardId:null,scanRewardId:null};
fetch("/config",{cache:"no-store"}).then(r=>r.json()).then(c=>{if(c?.assets?.basePath){document.querySelector(".hero img").src=`${c.assets.basePath}branding/branding.png`}}).catch(()=>{});
const $=id=>document.getElementById(id);
const msg=(id,text)=>$(id).textContent=text;
async function api(path,options={}){const headers={"Content-Type":"application/json",...(options.headers||{})};if(state.token)headers.Authorization=`Bearer ${state.token}`;const r=await fetch(path,{...options,headers,cache:"no-store"});const data=await r.json().catch(()=>({ok:false,error:"INVALID_RESPONSE"}));if(!r.ok)throw new Error(data.message||data.error||`HTTP ${r.status}`);return data}
function showRole(){ $("auth").hidden=true; if(state.role==="CUSTOMER")$("customer").hidden=false; if(state.role==="STAFF")$("staff").hidden=false; if(state.role==="OWNER")$("owner").hidden=false; }
$("requestOtp").onclick=async()=>{try{const phone=$("phone").value.trim();const d=await api("/auth/request-otp",{method:"POST",body:JSON.stringify({phone})});state.challengeId=d.challengeId;$("otpBox").hidden=false;msg("authMsg",d.devOtp?`OTP test: ${d.devOtp}`:"OTP terkirim. Berlaku 5 menit.")}catch(e){msg("authMsg",e.message)}};
$("verifyOtp").onclick=async()=>{try{const d=await api("/auth/verify-otp",{method:"POST",body:JSON.stringify({phone:$("phone").value.trim(),challengeId:state.challengeId,otp:$("otp").value.trim()})});state.token=d.token;state.role=d.role;state.userId=d.userId;showRole();msg("authMsg","")}catch(e){msg("authMsg",e.message)}};
let timer=0,raf=0,score=0,coins=[];const canvas=$("game"),ctx=canvas.getContext("2d");
function spawn(){coins.push({x:12+Math.random()*(canvas.width-24),y:20+Math.random()*(canvas.height-40),r:13})}
function draw(){ctx.clearRect(0,0,canvas.width,canvas.height);ctx.fillStyle="#2e7d32";ctx.font="700 16px system-ui";ctx.fillText("TANGKAP KOIN",12,24);for(const c of coins){ctx.beginPath();ctx.arc(c.x,c.y,c.r,0,Math.PI*2);ctx.fillStyle="#e5b72b";ctx.fill();ctx.strokeStyle="#7b5c00";ctx.stroke()}raf=requestAnimationFrame(draw)}
function hit(x,y){for(let i=coins.length-1;i>=0;i--){const c=coins[i];if(Math.hypot(x-c.x,y-c.y)<=c.r+18){coins.splice(i,1);score+=10;$("score").textContent=score;spawn();break}}}
canvas.onpointerdown=e=>{const r=canvas.getBoundingClientRect();hit((e.clientX-r.left)*canvas.width/r.width,(e.clientY-r.top)*canvas.height/r.height)};
async function finish(){cancelAnimationFrame(raf);$("gameBox").hidden=true;try{const d=await api("/finish",{method:"POST",body:JSON.stringify({playId:state.playId,sessionId:state.sessionId,result:{score},idempotencyKey:crypto.randomUUID()})});state.rewardId=d.rewardId;msg("gameMsg","Kamu menang. Klaim reward.");const b=document.createElement("button");b.textContent="Klaim Reward";b.onclick=claim;$("gameMsg").after(b)}catch(e){msg("gameMsg",e.message)}}
async function start(){try{score=0;coins=[];spawn();state.playId=null;const d=await api("/start",{method:"POST",body:JSON.stringify({transactionId:$("transactionId").value.trim(),idempotencyKey:crypto.randomUUID()})});state.playId=d.playId;state.sessionId=d.sessionId;$("gameBox").hidden=false;$("score").textContent="0";let end=Date.now()+15000;function tick(){timer=Math.max(0,Math.ceil((end-Date.now())/1000));$("time").textContent=timer;if(timer<=0){finish();return}setTimeout(tick,200)}tick();draw()}catch(e){msg("gameMsg",e.message)}}
async function claim(){try{const d=await api("/claim",{method:"POST",body:JSON.stringify({rewardId:state.rewardId,idempotencyKey:crypto.randomUUID()})});$("rewardBox").hidden=false;$("rewardTitle").textContent="REWARD BERHASIL DIKLAIM";$("rewardType").textContent=d.rewardType;$("token").textContent=d.tokenRef;$("qr").innerHTML=makeQrSvg(d.tokenRef)}catch(e){msg("gameMsg",e.message)}}
$("startGame").onclick=start;
async function scan(){try{const token=$("scanToken").value.trim();if(!token)throw new Error("QR token tidak ditemukan.");const d=await api(`/staff/scan/${encodeURIComponent(token)}`);state.scanRewardId=d.rewardId;if(d.redeemable){const redeemed=await api("/staff/redeem",{method:"POST",body:JSON.stringify({rewardId:d.rewardId})});$("staffResult").textContent=JSON.stringify({...d,redeem:redeemed},null,2)}else{$("staffResult").textContent=JSON.stringify(d,null,2)}}catch(e){$("staffResult").textContent=e.message}}

let cameraStream=null;
$("scanCamera").onclick=async()=>{if(!("BarcodeDetector" in window)){msg("scannerSupport","Browser ini tidak menyediakan pemindai QR native.");return}try{const detector=new BarcodeDetector({formats:["qr_code"]});const video=$("camera");cameraStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:"environment"},audio:false});video.srcObject=cameraStream;video.hidden=false;async function loop(){if(video.hidden)return;try{const codes=await detector.detect(video);if(codes[0]?.rawValue){$("scanToken").value=codes[0].rawValue;video.hidden=true;cameraStream.getTracks().forEach(t=>t.stop());cameraStream=null;await scan();return}}catch{}requestAnimationFrame(loop)}loop()}catch(e){msg("scannerSupport",e.message)}};
$("loadOwner").onclick=async()=>{try{const d=await api("/owner/overview");$("ownerResult").textContent=JSON.stringify(d,null,2)}catch(e){$("ownerResult").textContent=e.message}};

// Minimal QR encoder: QR version 5-L, byte mode, mask 0. No external library.
function makeQrSvg(text){const n=37,m=Array.from({length:n},()=>Array(n).fill(null));const set=(x,y,v)=>{if(x>=0&&y>=0&&x<n&&y<n)m[y][x]=v};function finder(cx,cy){for(let y=-1;y<=7;y++)for(let x=-1;x<=7;x++){const on=x>=0&&x<=6&&y>=0&&y<=6&&(x===0||x===6||y===0||y===6||(x>=2&&x<=4&&y>=2&&y<=4));set(cx+x,cy+y,on)}}finder(0,0);finder(n-7,0);finder(0,n-7);for(let i=8;i<n-8;i++){set(i,6,i%2===0);set(6,i,i%2===0)}for(const [cx,cy] of [[6,30],[30,6],[30,30]]){if(m[cy]?.[cx]!==null)continue;for(let y=-2;y<=2;y++)for(let x=-2;x<=2;x++)set(cx+x,cy+y,Math.max(Math.abs(x),Math.abs(y))===2||Math.max(Math.abs(x),Math.abs(y))===0)}set(8,n-8,true);for(let i=0;i<9;i++){if(m[i][8]===null)m[i][8]=false;if(m[8][i]===null)m[8][i]=false}for(let i=0;i<8;i++){if(m[n-1-i][8]===null)m[n-1-i][8]=false;if(m[8][n-1-i]===null)m[8][n-1-i]=false}
const bytes=Array.from(new TextEncoder().encode(text));if(bytes.length>106)throw new Error("QR text too long");const dataBits=[0,1,0,0];for(let i=7;i>=0;i--)dataBits.push((bytes.length>>i)&1);for(const b of bytes)for(let i=7;i>=0;i--)dataBits.push((b>>i)&1);for(let i=0;i<4&&dataBits.length<108*8;i++)dataBits.push(0);while(dataBits.length%8)dataBits.push(0);let padIndex=0;while(dataBits.length<108*8){const pad=[0xEC,0x11][padIndex++%2];for(let i=7;i>=0;i--)dataBits.push((pad>>i)&1)}const data=[];for(let i=0;i<108*8;i+=8){let v=0;for(let j=0;j<8;j++)v=(v<<1)|dataBits[i+j];data.push(v)}const exp=new Uint8Array(512),log=new Int16Array(256);let xg=1;for(let i=0;i<255;i++){exp[i]=xg;log[xg]=i;xg<<=1;if(xg&0x100)xg^=0x11d}for(let i=255;i<512;i++)exp[i]=exp[i-255];const mul=(a,b)=>a&&b?exp[log[a]+log[b]]:0;let gen=[1];for(let i=0;i<26;i++){const next=new Array(gen.length+1).fill(0);for(let j=0;j<gen.length;j++){next[j]^=gen[j];next[j+1]^=mul(gen[j],exp[i])}gen=next}const ecc=new Array(26).fill(0);for(const b of data){const f=b^ecc[0];for(let j=0;j<25;j++)ecc[j]=ecc[j+1]^mul(f,gen[j+1]);ecc[25]=mul(f,gen[26])}const codewords=data.concat(ecc);const bits=[];for(const b of codewords)for(let i=7;i>=0;i--)bits.push((b>>i)&1);let k=0,up=true;for(let x=n-1;x>0;x-=2){if(x===6)x--;for(let yy=0;yy<n;yy++){const y=up?n-1-yy:yy;for(let xx=0;xx<2;xx++){const col=x-xx;if(m[y][col]!==null)continue;let v=bits[k++]||0;v^=((y+col)%2===0)?1:0; m[y][col]=!!v}}up=!up}let format=((1<<3)|0);function bch(v,p){let d=v<<10;while(d.toString(2).length>=p.toString(2).length)d^=p<<(d.toString(2).length-p.toString(2).length);return d}let f=((format<<10)|bch(format,0x537))^0x5412;const fmt=[];for(let i=0;i<15;i++)fmt.push((f>>i)&1);let idx=0;for(let i=0;i<15;i++){let y;if(i<6)y=i;else if(i<8)y=i+1;else y=n-15+i;m[y][8]=!!fmt[idx++]}idx=0;for(let i=0;i<15;i++){let x;if(i<8)x=n-i-1;else if(i===8)x=7;else x=15-i-1;m[8][x]=!!fmt[idx++]}m[n-8][8]=true;let s=6;let svg=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${n+2*s} ${n+2*s}" shape-rendering="crispEdges"><rect width="100%" height="100%" fill="white"/>`;for(let y=0;y<n;y++)for(let x=0;x<n;x++)if(m[y][x])svg+=`<rect x="${x+s}" y="${y+s}" width="1" height="1"/>`;return svg+"</svg>"}
